language: ruby
rvm:
  - '1.9.3'
  - '2.1'
  - '2.2'
  - '2.3'
  - '2.4'
  - 'ruby-head'

script:
  rspec

sudo: false

before_install:
  - gem install rspec

notifications:
  recipients:
    - deepakmahakale@gmail.com
